### Importar librería

In [1]:
import numpy as np

```.copy()``` nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [2]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tomamos un trozo del array original

In [3]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

Queremos pasar todas nuestras variables a 0

In [4]:
# Cambios 
trozo_de_arr[:] = 0

# Mostrar slice nuevamete
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.

In [5]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Con .copy() creamos una copia para no dañar nuestro array original

In [6]:
# Para obtener una copia es necesario usar el método copy()
arr_copy = arr.copy()

Repetimos el mismo caso anterior pero cambiamos los valores dentro de la array por 100

In [7]:
arr_copy[:] = 100

In [8]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])